### ISSUE TITLE
Comparison with more popular libraries

### ISSUE THREAD

**Issue by dandv** [amgadfahmi/js-binarysearch#6]
There were already several binary search libraries on npm when this one was published. I'm curious what the [rationale](https://github.com/mikolalysenko/binary-search-bounds#rationale) was for writing a new library, and how this one differentiates from more battle-tested ones.

**Comment by amgadfahmi** [comment]
@dandv the main reason i designed this, that it has the capabilities to **search inside objects** which i needed in different projects. I see also syntax wise this one looks much readable.
To be fair, the other library is much older (started 2013) and am sure it got more testing than this one. 
Also the mentioned lib has more features like:
- Returns the index of the last item in the array <= y. This is a predecessor query which also returns the item if present.
- Returns the index of the first item in the array >= y. This is a successor query which also returns the 
- Returns an index of some item in the array == y or -1 if the item is not present. 

If  I got more requests about other features, i can work on it and make a new release
